export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_USER_DATA = 'SET_USER_DATA';
export const FETCH_USER_DATA_FAILED = 'FETCH_USER_DATA_FAILED';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_USER_DATA_START = 'UPDATE_USER_DATA_START';
export const UPDATE_USER_DATA_FAILED = 'UPDATE_USER_DATA_FAILED';

export const POST_APPOINTMENT_DATA = 'POST_APPOINTMENT_DATA';
export const POST_APPOINTMENT_DATA_FAILED = 'POST_APPOINTMENT_DATA_FAILED';

export const FETCH_APPOINTMENT_DATA_START = 'FETCH_APPOINTMENT_DATA_START';
export const SET_APPOINTMENT_DATA = 'SET_APPOINTMENT_DATA';
export const FETCH_APPOINTMENT_DATA_FAILED = 'FETCH_APPOINTMENT_DATA_FAILED';

export const UPLOAD_PHOTO_START = 'UPLOAD_PHOTO_START';
export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const SET_PHOTO = 'SET_PHOTO';
export const SET_PHOTO_URL = 'SET_PHOTO_URL';